import {IWordDTO} from "../models/WordDTO";

export const advanced: IWordDTO[] = [
    {id: 1, eng: 'hi', rus: 'привет'},
    {id: 2, eng: 'hello', rus: 'здравствуйте, привет'},
    {id: 3, eng: 'sorry', rus: 'извинитк'},
    {id: 4, eng: 'please', rus: 'пожалуйста (прошу)'},
    {id: 5, eng: 'thank you', rus: 'спасибо'},
    {id: 6, eng: 'you are welcome', rus: 'пожалуйста, незачто'},
    {id: 7, eng: 'what a pity', rus: 'как жаль'},
    {id: 8, eng: '(good)bye', rus: 'досвидания'},
    {id: 9, eng: 'people', rus: 'люди'},
    {id: 10, eng: 'man', rus: 'мужчина'},
    {id: 11, eng: 'woman', rus: 'женщина'},
    {id: 12, eng: 'child', rus: 'ребенок'},
    {id: 13, eng: 'boy', rus: 'мальчик'},
    {id: 14, eng: 'girl', rus: 'девочка'},
    {id: 15, eng: 'guy', rus: 'парень'},
    {id: 16, eng: 'friend', rus: 'друг'},
    {id: 17, eng: 'acquaintance', rus: 'знакомый; знакомство'},
    {id: 18, eng: 'neighbor', rus: 'сосед'},
    {id: 19, eng: 'guest', rus: 'гость'},
    {id: 20, eng: 'chief', rus: 'начальник; шеф; главный; вождь'},
    {id: 21, eng: 'boss', rus: 'босс'},
    {id: 22, eng: 'competitor', rus: 'конкурент, соперник'},
    {id: 23, eng: 'client', rus: 'клиент'},
    {id: 24, eng: 'colleague', rus: 'коллега'},
    {id: 25, eng: 'family', rus: 'семья'},
    {id: 26, eng: 'parents', rus: 'родители'},
    {id: 27, eng: 'father', rus: 'отец'},
    {id: 28, eng: 'dad (dy)', rus: 'папа'},
    {id: 29, eng: 'mother', rus: 'мать'},
    {id: 30, eng: 'mum (my)', rus: 'мама'},
    {id: 31, eng: 'husband', rus: 'муж'},
    {id: 32, eng: 'wife', rus: 'жена'},
    {id: 33, eng: 'son', rus: 'сын'},
    {id: 34, eng: 'daughter', rus: 'дочь'},
    {id: 35, eng: 'brother', rus: 'брат'},
    {id: 36, eng: 'sister', rus: 'сестра'},
    {id: 37, eng: 'grandfather', rus: 'дед…'},
    {id: 38, eng: 'father-in-law', rus: 'тесть, свекор…'},
    {id: 39, eng: 'uncle', rus: 'дядя'},
    {id: 40, eng: 'aunt', rus: 'тетя'},
    {id: 41, eng: 'cousin', rus: 'двоюродный брат, двоюродная сестра'},
    {id: 42, eng: 'nephew', rus: 'племянник'},
    {id: 43, eng: 'niece', rus: 'племянница'},
    {id: 44, eng: 'job', rus: 'работа'},
    {id: 45, eng: 'businessman', rus: 'предприниматель'},
    {id: 46, eng: 'teacher', rus: 'учитель'},
    {id: 47, eng: 'driver', rus: 'водитель'},
    {id: 48, eng: 'worker', rus: 'рабочий'},
    {id: 49, eng: 'engineer', rus: 'инженер'},
    {id: 50, eng: 'doctor', rus: 'врач'},
    {id: 51, eng: 'lawyer', rus: 'адвокат, юрист'},
    {id: 52, eng: 'journalist', rus: 'журналист'},
    {id: 53, eng: 'nurse', rus: 'медсестра'},
    {id: 54, eng: 'shop assistant', rus: 'продавец'},
    {id: 55, eng: 'waiter', rus: 'официант'},
    {id: 56, eng: 'accountant', rus: 'бухгалтер'},
    {id: 57, eng: 'artist', rus: 'художник'},
    {id: 58, eng: 'musician', rus: 'музыкант'},
    {id: 59, eng: 'actor', rus: 'актер'},
    {id: 60, eng: 'student', rus: 'студент'},
    {id: 61, eng: 'pupil', rus: 'школьник, ученик'},
    {id: 62, eng: 'animal', rus: 'животное'},
    {id: 63, eng: 'cat', rus: 'кошка'},
    {id: 64, eng: 'dog', rus: 'собака'},
    {id: 65, eng: 'bird', rus: 'птица'},
    {id: 66, eng: 'squirrel', rus: 'белка'},
    {id: 67, eng: 'wolf', rus: 'волк'},
    {id: 68, eng: 'goose', rus: 'гусь'},
    {id: 69, eng: 'giraffe', rus: 'жираф'},
    {id: 70, eng: 'rabbit', rus: 'кролик; заяц'},
    {id: 71, eng: 'cow', rus: 'корова'},
    {id: 72, eng: 'rat', rus: 'крыса'},
    {id: 73, eng: 'fox', rus: 'лиса'},
    {id: 74, eng: 'horse', rus: 'лошадь'},
    {id: 75, eng: 'frog', rus: 'лягушка'},
    {id: 76, eng: 'bear', rus: 'медведь'},
    {id: 77, eng: 'mouse', rus: 'мышь'},
    {id: 78, eng: 'monkey', rus: 'обезьяна'},
    {id: 79, eng: 'pig', rus: 'свинья'},
    {id: 80, eng: 'elephant', rus: 'слон'},
    {id: 81, eng: 'duck', rus: 'утка'},
    {id: 82, eng: 'country', rus: 'страна; сельская местность'},
    {id: 83, eng: 'Russia', rus: 'Россия'},
    {id: 84, eng: 'Great Britain', rus: 'Великобритания'},
    {id: 85, eng: 'England', rus: 'Англия'},
    {id: 86, eng: 'city', rus: 'город'},
    {id: 87, eng: 'house', rus: 'дом (здание)'},
    {id: 88, eng: 'home', rus: 'дом (место проживания)'},
    {id: 89, eng: 'building', rus: 'здание; строительство'},
    {id: 90, eng: 'place', rus: 'место; помещать'},
    {id: 91, eng: 'entrance', rus: 'вход'},
    {id: 92, eng: 'exit', rus: 'выход'},
    {id: 93, eng: 'center', rus: 'центр'},
    {id: 94, eng: 'yard', rus: 'двор'},
    {id: 95, eng: 'roof', rus: 'крыша'},
    {id: 96, eng: 'fence', rus: 'забор'},
    {id: 97, eng: 'land', rus: 'земля, участок'},
    {id: 98, eng: 'village', rus: 'деревня, поселок'},
    {id: 99, eng: 'school', rus: 'школа'},
    {id: 100, eng: 'university', rus: 'университет'},
    {id: 101, eng: 'theater', rus: 'театр'},
    {id: 102, eng: 'church', rus: 'церковь'},
    {id: 103, eng: 'restaurant', rus: 'ресторан'},
    {id: 104, eng: 'cafe', rus: 'кафе'},
    {id: 105, eng: 'hotel', rus: 'гостиница'},
    {id: 106, eng: 'bank', rus: 'банк'},
    {id: 107, eng: 'cinema', rus: 'кинотеатр'},
    {id: 108, eng: 'hospital', rus: 'больница'},
    {id: 109, eng: 'police', rus: 'полиция'},
    {id: 110, eng: 'post office', rus: 'почта'},
    {id: 111, eng: 'station', rus: 'станция, вокзал'},
    {id: 112, eng: 'airport', rus: 'аэропорт'},
    {id: 113, eng: 'shop', rus: 'магазин'},
    {id: 114, eng: 'pharmacy', rus: 'аптека'},
    {id: 115, eng: 'market', rus: 'рынок'},
    {id: 116, eng: 'office', rus: 'офис'},
    {id: 117, eng: 'company', rus: 'компания, фирма'},
    {id: 118, eng: 'factory', rus: 'предприятие, завод, фабрика'},
    {id: 119, eng: 'square', rus: 'площадь'},
    {id: 120, eng: 'street', rus: 'улица'},
    {id: 121, eng: 'road', rus: 'дорога'},
    {id: 122, eng: 'crossroads', rus: 'перекрёсток'},
    {id: 123, eng: 'stop', rus: 'остановка; останавливаться'},
    {id: 124, eng: 'sidewalk', rus: 'тротуар'},
    {id: 125, eng: 'path', rus: 'тропа, тропинка'},
    {id: 126, eng: 'garden', rus: 'сад'},
    {id: 127, eng: 'park', rus: 'парк'},
    {id: 128, eng: 'bridge', rus: 'мост'},
    {id: 129, eng: 'river', rus: 'река'},
    {id: 130, eng: 'forest', rus: 'лес'},
    {id: 131, eng: 'field', rus: 'поле'},
    {id: 132, eng: 'mountain', rus: 'гора'},
    {id: 133, eng: 'lake', rus: 'озеро'},
    {id: 134, eng: 'sea', rus: 'море'},
    {id: 135, eng: 'ocean', rus: 'океан'},
    {id: 136, eng: 'coast', rus: 'морской берег, побережье'},
    {id: 137, eng: 'beach', rus: 'пляж'},
    {id: 138, eng: 'sand', rus: 'песок'},
    {id: 139, eng: 'island', rus: 'остров'},
    {id: 140, eng: 'border', rus: 'граница'},
    {id: 141, eng: 'customs', rus: 'таможня'},
    {id: 142, eng: 'garbage', rus: 'мусор'},
    {id: 143, eng: 'waste', rus: 'отходы; тратить впустую'},
    {id: 144, eng: 'stone', rus: 'камень'},
    {id: 145, eng: 'plant', rus: 'растение; завод; сажать'},
    {id: 146, eng: 'tree', rus: 'дерево'},
    {id: 147, eng: 'grass', rus: 'трава'},
    {id: 148, eng: 'flower', rus: 'цветок'},
    {id: 149, eng: 'leaf', rus: 'лист (дерева)'},
    {id: 150, eng: 'flat', rus: 'квартира'},
    {id: 151, eng: 'room', rus: 'комната'},
    {id: 152, eng: 'living room', rus: 'зал'},
    {id: 153, eng: 'bedroom', rus: 'спальня'},
    {id: 154, eng: 'bathroom', rus: 'ванная'},
    {id: 155, eng: 'shower', rus: 'душ'},
    {id: 156, eng: 'toilet', rus: 'туалет'},
    {id: 157, eng: 'kitchen', rus: 'кухня'},
    {id: 158, eng: 'hall', rus: 'коридор'},
    {id: 159, eng: 'balcony', rus: 'балкон'},
    {id: 160, eng: 'floor', rus: 'пол;этаж'},
    {id: 161, eng: 'ceiling', rus: 'потолок'},
    {id: 162, eng: 'wall', rus: 'стена'},
    {id: 163, eng: 'stairs', rus: 'ступеньки; лестница'},
    {id: 164, eng: 'door', rus: 'дверь'},
    {id: 165, eng: 'window', rus: 'окно'},
    {id: 166, eng: 'windowsill', rus: 'подоконник'},
    {id: 167, eng: 'curtain', rus: 'занавес (ка),штора'},
    {id: 168, eng: 'switch', rus: 'выключатель; переключать'},
    {id: 169, eng: 'socket', rus: 'розетка'},
    {id: 170, eng: 'faucet', rus: '(водопроводный) кран'},
    {id: 171, eng: 'pipe', rus: 'труба; трубка'},
    {id: 172, eng: 'chimney', rus: 'дымовая труба'},
    {id: 173, eng: 'furniture', rus: 'мебель'},
    {id: 174, eng: 'table', rus: 'стол'},
    {id: 175, eng: 'chair', rus: 'стул'},
    {id: 176, eng: 'armchair', rus: 'кресло'},
    {id: 177, eng: 'sofa', rus: 'диван'},
    {id: 178, eng: 'bed', rus: 'кровать'},
    {id: 179, eng: 'wardrobe', rus: '(платяной) шкаф'},
    {id: 180, eng: 'cabinet', rus: 'шкаф (чик)'},
    {id: 181, eng: 'shelf', rus: 'полка'},
    {id: 182, eng: 'mirror', rus: 'зеркало'},
    {id: 183, eng: 'carpet', rus: 'ковер'},
    {id: 184, eng: 'fridge', rus: 'холодильник'},
    {id: 185, eng: 'microwave', rus: 'микроволновка'},
    {id: 186, eng: 'oven', rus: 'печь, духовка'},
    {id: 187, eng: 'stove', rus: 'кухонная плита'},
    {id: 188, eng: 'food', rus: 'еда'},
    {id: 189, eng: 'bread', rus: 'хлеб'},
    {id: 190, eng: 'butter', rus: 'масло'},
    {id: 191, eng: 'oil', rus: 'растительное масло; нефть'},
    {id: 192, eng: 'cheese', rus: 'сыр'},
    {id: 193, eng: 'sausage', rus: 'колбаса, сосиска'},
    {id: 194, eng: 'ham', rus: 'ветчина'},
    {id: 195, eng: 'meat', rus: 'мясо'},
    {id: 196, eng: 'beef', rus: 'говядина'},
    {id: 197, eng: 'pork', rus: 'свинина'},
    {id: 198, eng: 'lamb', rus: 'баранина; ягненок'},
    {id: 199, eng: 'chicken', rus: 'цыпленок; курица'},
    {id: 200, eng: 'cutlet', rus: 'котлета'},
    {id: 201, eng: 'fish', rus: 'рыба; рыбачить'},
    {id: 202, eng: 'egg', rus: 'яйцо'},
    {id: 203, eng: 'salad', rus: 'салат'},
    {id: 204, eng: 'mushroom', rus: 'гриб'},
    {id: 205, eng: 'corn', rus: 'кукуруза; зерно'},
    {id: 206, eng: 'porridge', rus: 'каша'},
    {id: 207, eng: 'oatmeal', rus: 'овсянка'},
    {id: 208, eng: 'soup', rus: 'суп'},
    {id: 209, eng: 'sandwich', rus: 'бутерброд'},
    {id: 210, eng: 'rice', rus: 'рис'},
    {id: 211, eng: 'noodles', rus: 'лапша'},
    {id: 212, eng: 'flour', rus: 'мука'},
    {id: 213, eng: 'spice', rus: 'специя, пряность'},
    {id: 214, eng: 'pepper', rus: 'перец; поперчить'},
    {id: 215, eng: 'salt', rus: 'соль; посолить'},
    {id: 216, eng: 'onion', rus: 'лук (репчатый)'},
    {id: 217, eng: 'garlic', rus: 'чеснок'},
    {id: 218, eng: 'sauce', rus: 'соус'},
    {id: 219, eng: 'vegetables', rus: 'овощи'},
    {id: 220, eng: 'potatoes', rus: 'картофель'},
    {id: 221, eng: 'carrot', rus: 'морковь'},
    {id: 222, eng: 'beet', rus: 'свекла'},
    {id: 223, eng: 'tomato', rus: 'помидор'},
    {id: 224, eng: 'cucumber', rus: 'огурец'},
    {id: 225, eng: 'cabbage', rus: 'капуста'},
    {id: 226, eng: 'squash', rus: 'кабачок'},
    {id: 227, eng: 'eggplant', rus: 'баклажан'},
    {id: 228, eng: 'beans', rus: 'бобы'},
    {id: 229, eng: 'pea', rus: 'горох'},
    {id: 230, eng: 'nut', rus: 'орех'},
    {id: 231, eng: 'fruit', rus: 'фрукт (ы);плод'},
    {id: 232, eng: 'apple', rus: 'яблоко'},
    {id: 233, eng: 'pear', rus: 'груша'},
    {id: 234, eng: 'banana', rus: 'банан'},
    {id: 235, eng: 'berry', rus: 'ягода'},
    {id: 236, eng: 'strawberry', rus: 'клубника, земляника'},
    {id: 237, eng: 'raspberry', rus: 'малина'},
    {id: 238, eng: 'cherry', rus: 'вишня'},
    {id: 239, eng: 'plum', rus: 'слива'},
    {id: 240, eng: 'grape', rus: 'виноград'},
    {id: 241, eng: 'apricot', rus: 'абрикос'},
    {id: 242, eng: 'peach', rus: 'персик'},
    {id: 243, eng: 'melon', rus: 'дыня'},
    {id: 244, eng: 'watermelon', rus: 'арбуз'},
    {id: 245, eng: 'pumpkin', rus: 'тыква'},
    {id: 246, eng: 'orange', rus: 'апельсин; оранжевый'},
    {id: 247, eng: 'mandarin', rus: 'мандарин'},
    {id: 248, eng: 'lemon', rus: 'лимон'},
    {id: 249, eng: 'pineapple', rus: 'ананас'},
    {id: 250, eng: 'sugar', rus: 'сахар'},
    {id: 251, eng: 'honey', rus: 'мёд'},
    {id: 252, eng: 'jam', rus: 'варенье'},
    {id: 253, eng: 'cake', rus: 'торт'},
    {id: 254, eng: 'bun', rus: 'булочка'},
    {id: 255, eng: 'cookie', rus: 'печенье'},
    {id: 256, eng: 'pie', rus: 'пирог, пирожок'},
    {id: 257, eng: 'sweet', rus: 'конфета; сладкий'},
    {id: 258, eng: 'ice-cream', rus: 'мороженое'},
    {id: 259, eng: 'chocolate', rus: 'шоколад'},
    {id: 260, eng: 'water', rus: 'вода; поливать'},
    {id: 261, eng: 'soda', rus: 'газировка'},
    {id: 262, eng: 'juice', rus: 'сок'},
    {id: 263, eng: 'wine', rus: 'вино'},
    {id: 264, eng: 'tea', rus: 'чай'},
    {id: 265, eng: 'coffee', rus: 'кофе'},
    {id: 266, eng: 'milk', rus: 'молоко'},
    {id: 267, eng: 'cream', rus: 'сливки; крем'},
    {id: 268, eng: 'yogurt', rus: 'йогурт'},
    {id: 269, eng: 'curd', rus: 'творог'},
    {id: 270, eng: 'dish', rus: 'посуда'},
    {id: 271, eng: 'cup', rus: 'чашка'},
    {id: 272, eng: 'glass', rus: 'стакан; стекло'},
    {id: 273, eng: 'mug', rus: 'кружка'},
    {id: 274, eng: 'plate', rus: 'тарелка'},
    {id: 275, eng: 'spoon', rus: 'ложка'},
    {id: 276, eng: 'ork', rus: 'вилка'},
    {id: 277, eng: 'knife', rus: 'нож'},
    {id: 278, eng: 'saucer', rus: 'блюдце'},
    {id: 279, eng: 'bottle', rus: 'бутылка'},
    {id: 280, eng: 'napkin', rus: 'салфетка'},
    {id: 281, eng: 'pan', rus: 'кастрюля'},
    {id: 282, eng: 'frying pan', rus: 'сковородка'},
    {id: 283, eng: 'kettle', rus: 'чайник; котел'},
    {id: 284, eng: 'meal', rus: 'принятие пищи,еда'},
    {id: 285, eng: 'breakfast', rus: 'завтрак'},
    {id: 286, eng: 'lunch', rus: 'обед'},
    {id: 287, eng: 'dinner', rus: 'ужин'},
    {id: 288, eng: 'transport', rus: 'транспорт'},
    {id: 289, eng: 'plane', rus: 'самолет'},
    {id: 290, eng: 'car', rus: 'автомобиль'},
    {id: 291, eng: 'tram', rus: 'трамвай'},
    {id: 292, eng: 'bus', rus: 'автобус'},
    {id: 293, eng: 'train', rus: 'поезд'},
    {id: 294, eng: 'ship', rus: 'корабль'},
    {id: 295, eng: 'bicycle', rus: 'велосипед'},
    {id: 296, eng: 'time', rus: 'время; раз'},
    {id: 297, eng: 'minute', rus: 'минута'},
    {id: 298, eng: 'hour', rus: 'час'},
    {id: 299, eng: 'week', rus: 'неделя'},
    {id: 300, eng: 'year', rus: 'год'},
    {id: 301, eng: 'century', rus: 'век, столетие'},
    {id: 302, eng: 'the day before yesterday', rus: 'позавчера'},
    {id: 303, eng: 'yesterday', rus: 'вчера'},
    {id: 304, eng: 'today', rus: 'сегодня (днем)'},
    {id: 305, eng: 'tonight', rus: 'сегодня вечером (ночью)'},
    {id: 306, eng: 'tomorrow', rus: 'завтра'},
    {id: 307, eng: 'the day after tomorrow', rus: 'послезавтра'},
    {id: 308, eng: 'day', rus: 'день'},
    {id: 309, eng: 'morning', rus: 'утро'},
    {id: 310, eng: 'afternoon', rus: 'полдень'},
    {id: 311, eng: 'evening', rus: 'вечер'},
    {id: 312, eng: 'night', rus: 'ночь'},
    {id: 313, eng: 'Monday', rus: 'понедельник'},
    {id: 314, eng: 'Tuesday', rus: 'вторник'},
    {id: 315, eng: 'Wednesday', rus: 'среда'},
    {id: 316, eng: 'Thursday', rus: 'четверг'},
    {id: 317, eng: 'Friday', rus: 'пятница'},
    {id: 318, eng: 'Saturday', rus: 'суббота'},
    {id: 319, eng: 'Sunday', rus: 'воскресенье'},
    {id: 320, eng: 'month', rus: 'месяц'},
    {id: 321, eng: 'January', rus: 'январь'},
    {id: 322, eng: 'February', rus: 'февраль'},
    {id: 323, eng: 'March', rus: 'март'},
    {id: 324, eng: 'April', rus: 'апрель'},
    {id: 325, eng: 'May', rus: 'май'},
    {id: 326, eng: 'June', rus: 'июнь'},
    {id: 327, eng: 'July', rus: 'июль'},
    {id: 328, eng: 'August', rus: 'август'},
    {id: 329, eng: 'September', rus: 'сентябрь'},
    {id: 330, eng: 'October', rus: 'октябрь'},
    {id: 331, eng: 'November', rus: 'ноябрь'},
    {id: 332, eng: 'December', rus: 'декабрь'},
    {id: 333, eng: 'season', rus: 'время года;сезон'},
    {id: 334, eng: 'spring', rus: 'весна'},
    {id: 335, eng: 'summer', rus: 'лето'},
    {id: 336, eng: 'autumn', rus: 'осень'},
    {id: 337, eng: 'winter', rus: 'зима'},
    {id: 338, eng: 'holiday', rus: 'праздник; отпуск; каникулы'},
    {id: 339, eng: 'Christmas', rus: 'Рождество'},
    {id: 340, eng: 'Easter', rus: 'Пасха'},
    {id: 341, eng: 'birthday', rus: 'день рождения'},
    {id: 342, eng: 'form', rus: 'анкета;'},
    {id: 343, eng: 'name', rus: 'имя, фамилия; название; называть'},
    {id: 344, eng: 'first name', rus: 'имя'},
    {id: 345, eng: 'surname', rus: 'фамилия'},
    {id: 346, eng: 'maiden name', rus: 'девичья фамилия'},
    {id: 347, eng: 'birth date', rus: 'дата рождения'},
    {id: 348, eng: 'place of birth', rus: 'место рождения'},
    {id: 349, eng: 'address', rus: 'адрес'},
    {id: 350, eng: 'marital status', rus: 'семейное положение'},
    {id: 351, eng: 'single', rus: 'один(окий)'},
    {id: 352, eng: 'married', rus: 'женатый/замужняя'},
    {id: 353, eng: 'divorced', rus: 'разведенный'},
    {id: 354, eng: 'widowed', rus: 'овдовевший'},
    {id: 355, eng: 'thing', rus: 'вещь'},
    {id: 356, eng: 'pen', rus: 'ручка'},
    {id: 357, eng: 'pencil', rus: 'карандаш'},
    {id: 358, eng: 'book', rus: 'книга'},
    {id: 359, eng: 'copybook', rus: 'тетрадь'},
    {id: 360, eng: 'notebook', rus: 'блокнот'},
    {id: 361, eng: 'note', rus: 'записка, запись'},
    {id: 362, eng: 'dictionary', rus: 'словарь'},
    {id: 363, eng: 'letter', rus: 'письмо; буква'},
    {id: 364, eng: 'envelope', rus: 'конверт'},
    {id: 365, eng: 'paper', rus: 'бумага'},
    {id: 366, eng: 'newspaper', rus: 'газета'},
    {id: 367, eng: 'magazine', rus: 'журнал'},
    {id: 368, eng: 'phone', rus: 'телефон'},
    {id: 369, eng: 'clock', rus: 'часы'},
    {id: 370, eng: 'comb', rus: 'расчёска; расчесывать'},
    {id: 371, eng: 'TV (-set)', rus: 'телевизор'},
    {id: 372, eng: 'iron', rus: 'утюг; железо; гладить (утюгом)'},
    {id: 373, eng: 'soap', rus: 'мыло; намыливать'},
    {id: 374, eng: 'radio', rus: 'радио'},
    {id: 375, eng: 'bag', rus: 'сумка'},
    {id: 376, eng: 'backpack', rus: 'рюкзак'},
    {id: 377, eng: 'map', rus: 'карта'},
    {id: 378, eng: 'card', rus: 'открытка; карточка'},
    {id: 379, eng: 'suitcase', rus: 'чемодан'},
    {id: 380, eng: 'present', rus: 'подарок'},
    {id: 381, eng: 'camera', rus: 'фотоаппарат; видеокамера'},
    {id: 382, eng: 'vase', rus: 'ваза'},
    {id: 383, eng: 'handkerchief', rus: 'носовой платок'},
    {id: 384, eng: 'ball', rus: 'мяч'},
    {id: 385, eng: 'balloon', rus: 'воздушный шар (ик)'},
    {id: 386, eng: 'toy', rus: 'игрушка'},
    {id: 387, eng: 'ticket', rus: 'билет'},
    {id: 388, eng: 'luggage', rus: 'багаж'},
    {id: 389, eng: 'battery', rus: 'батарейка, аккумулятор'},
    {id: 390, eng: 'bucket', rus: 'ведро'},
    {id: 391, eng: 'rope', rus: 'веревка'},
    {id: 392, eng: 'board', rus: 'доска; борт; совет (правление)'},
    {id: 393, eng: 'calendar', rus: 'календарь'},
    {id: 394, eng: 'laptop', rus: 'ноутбук'},
    {id: 395, eng: 'brush', rus: 'щетка; кисть, кисточка; чистить щеткой'},
    {id: 396, eng: 'keyboard', rus: 'клавиатура'},
    {id: 397, eng: 'key', rus: 'ключ; клавиша'},
    {id: 398, eng: 'wheel', rus: 'колесо'},
    {id: 399, eng: 'steering wheel', rus: 'руль'},
    {id: 400, eng: 'trunk', rus: 'багажник; ствол; хобот'},
    {id: 401, eng: 'gas (oline)', rus: 'бензин'},
    {id: 402, eng: 'purse', rus: 'дамская сумка; кошелек'},
    {id: 403, eng: 'wallet', rus: 'бумажник'},
    {id: 404, eng: 'lamp', rus: 'лампа'},
    {id: 405, eng: 'ruler', rus: 'линейка; правитель'},
    {id: 406, eng: 'shovel', rus: 'лопата; рыть'},
    {id: 407, eng: 'machine', rus: 'машина; механизм; аппарат; станок'},
    {id: 408, eng: 'hammer', rus: 'молоток; вбивать молотком'},
    {id: 409, eng: 'scissors', rus: 'ножницы'},
    {id: 410, eng: 'glasses', rus: 'очки'},
    {id: 411, eng: 'package', rus: 'посылка; упаковка'},
    {id: 412, eng: 'stick', rus: 'палка; придерживаться; втыкать'},
    {id: 413, eng: 'glue', rus: 'клей; приклеивать'},
    {id: 414, eng: 'gift', rus: 'подарок; дар'},
    {id: 415, eng: 'towel', rus: 'полотенце'},
    {id: 416, eng: 'mail', rus: 'почта (корреспонденция); отправлять попочте'},
    {id: 417, eng: 'wire', rus: 'проволока; провод'},
    {id: 418, eng: 'page', rus: 'страница'},
    {id: 419, eng: 'torch', rus: 'карманный фонарь; горелка; факел'},
    {id: 420, eng: 'box', rus: 'коробка, ящик; боксировать'},
    {id: 421, eng: 'blanket', rus: 'одеяло'},
    {id: 422, eng: 'sheet', rus: 'простыня; лист (ок)'},
    {id: 423, eng: 'pillow', rus: 'подушка'},
    {id: 424, eng: 'clothes', rus: 'одежда'},
    {id: 425, eng: 'body', rus: 'тело;кузов'},
    {id: 426, eng: 'head', rus: 'голова; глава, руководитель'},
    {id: 427, eng: 'face', rus: 'лицо'},
    {id: 428, eng: 'forehead', rus: 'лоб'},
    {id: 429, eng: 'nose', rus: 'нос'},
    {id: 430, eng: 'ear', rus: 'ухо; ушко;колос'},
    {id: 431, eng: 'mouth', rus: 'рот'},
    {id: 432, eng: 'throat', rus: 'горло'},
    {id: 433, eng: 'eye', rus: 'глаз'},
    {id: 434, eng: 'eyebrow', rus: 'бровь'},
    {id: 435, eng: 'lips', rus: 'губы'},
    {id: 436, eng: 'tooth', rus: 'зуб'},
    {id: 437, eng: 'hair', rus: 'волос (ы)'},
    {id: 438, eng: 'mustache', rus: 'усы'},
    {id: 439, eng: 'cheek', rus: 'щека; наглость, нахальство'},
    {id: 440, eng: 'chin', rus: 'подбородок'},
    {id: 441, eng: 'neck', rus: 'шея'},
    {id: 442, eng: 'shoulder', rus: 'плечо'},
    {id: 443, eng: 'chest', rus: 'грудь'},
    {id: 444, eng: 'heart', rus: 'сердце'},
    {id: 445, eng: 'stomach', rus: 'желудок; живот'},
    {id: 446, eng: 'back', rus: 'спина; назад'},
    {id: 447, eng: 'wrist', rus: 'запястье'},
    {id: 448, eng: 'hand', rus: 'рука, кисть (руки)'},
    {id: 449, eng: 'finger', rus: 'палец (руки)'},
    {id: 450, eng: 'nail', rus: 'ноготь; гвоздь; прибивать'},
    {id: 451, eng: 'elbow', rus: 'локоть'},
    {id: 452, eng: 'leg', rus: 'нога;ножка'},
    {id: 453, eng: 'knee', rus: 'колено'},
    {id: 454, eng: 'foot', rus: 'ступня'},
    {id: 455, eng: 'heel', rus: 'пятка; каблук'},
    {id: 456, eng: 'toe', rus: 'палец (ноги)'},
    {id: 457, eng: 'beard', rus: 'борода'},
    {id: 458, eng: 'bone', rus: 'кость'},
    {id: 459, eng: 'health', rus: 'здоровье'},
    {id: 460, eng: 'healthy', rus: 'здоровый'},
    {id: 461, eng: 'sick', rus: 'больной'},
    {id: 462, eng: 'sickness', rus: 'болезнь'},
    {id: 463, eng: 'fever', rus: 'жар, (высокая) температура'},
    {id: 464, eng: 'cough', rus: 'кашель; кашлять'},
    {id: 465, eng: 'running nose', rus: 'насморк'},
    {id: 466, eng: 'sneeze', rus: 'чихать'},
    {id: 467, eng: 'pain', rus: 'боль'},
    {id: 468, eng: 'headache', rus: 'головная боль'},
    {id: 469, eng: 'flu', rus: 'грипп'},
    {id: 470, eng: 'bruise', rus: 'синяк, ушиб; ушибить'},
    {id: 471, eng: 'event', rus: 'событие'},
    {id: 472, eng: 'birth', rus: 'рождение'},
    {id: 473, eng: 'game', rus: 'игра'},
    {id: 474, eng: 'lesson', rus: 'урок'},
    {id: 475, eng: 'vacation', rus: 'отпуск, каникулы'},
    {id: 476, eng: 'party', rus: 'вечеринка'},
    {id: 477, eng: 'meeting', rus: 'встреча; собрание'},
    {id: 478, eng: 'wedding', rus: 'свадьба'},
    {id: 479, eng: 'negotiation', rus: 'переговоры'},
    {id: 480, eng: 'trip', rus: 'поездка, путешествие'},
    {id: 481, eng: 'death', rus: 'смерть'},
    {id: 482, eng: 'weather', rus: 'погода'},
    {id: 483, eng: 'sun', rus: 'солнце'},
    {id: 484, eng: 'moon', rus: 'луна'},
    {id: 485, eng: 'wind', rus: 'ветер'},
    {id: 486, eng: 'fog', rus: 'туман'},
    {id: 487, eng: 'rain', rus: 'дождь'},
    {id: 488, eng: 'snow', rus: 'снег'},
    {id: 489, eng: 'sky', rus: 'небо'},
    {id: 490, eng: 'cloud', rus: 'облако'},
    {id: 491, eng: 'air', rus: 'воздух'},
    {id: 492, eng: 'temperature', rus: 'температура'},
    {id: 493, eng: 'degree', rus: 'градус; степень'},
    {id: 494, eng: 'distance', rus: 'расстояние; дистанция'},
    {id: 495, eng: 'length', rus: 'длина'},
    {id: 496, eng: 'height', rus: 'высота'},
    {id: 497, eng: 'depth', rus: 'глубина'},
    {id: 498, eng: 'strength', rus: 'сила; прочность'},
    {id: 499, eng: 'important', rus: 'важный'},
    {id: 500, eng: 'delicious', rus: 'очень вку'},
]