export const database = [
    {id: 5, eng: 'I', rus: 'я'},
    {id: 6, eng: 'you', rus: 'ты, вы'},
    {id: 7, eng: 'he', rus: 'он'},
    {id: 8, eng: 'she', rus: 'она'},
    {id: 9, eng: 'it', rus: 'оно'},
    {id: 10, eng: 'we', rus: 'мы'},
    {id: 11, eng: 'people', rus: 'люди'},
    {id: 12, eng: 'family', rus: 'семья'},
    {id: 13, eng: 'woman', rus: 'женщина'},
    {id: 14, eng: 'man', rus: 'мужчина'},
    {id: 15, eng: 'girl', rus: 'девочка'},
    {id: 16, eng: 'boy', rus: 'мальчик'},
    {id: 17, eng: 'child', rus: 'ребёнок'},
    {id: 18, eng: 'friend', rus: 'друг'},
    {id: 19, eng: 'husband', rus: 'муж'},
    {id: 20, eng: 'wife', rus: 'жена'},
    {id: 21, eng: 'name', rus: 'имя'},
    {id: 22, eng: 'head', rus: 'голова'},
    {id: 23, eng: 'face', rus: 'лицо'},
    {id: 24, eng: 'hand', rus: 'рука'},
    {id: 25, eng: 'life', rus: 'жизнь'},
    {id: 26, eng: 'hour', rus: 'час'},
    {id: 27, eng: 'week', rus: 'неделя'},
    {id: 28, eng: 'day', rus: 'день'},
    {id: 29, eng: 'night', rus: 'ночь'},
    {id: 30, eng: 'month', rus: 'месяц'},
    {id: 31, eng: 'year', rus: 'год'},
    {id: 32, eng: 'time', rus: 'время'},
    {id: 33, eng: 'world', rus: 'мир'},
    {id: 34, eng: 'sun', rus: 'солнце'},
    {id: 35, eng: 'animal', rus: 'животное'},
    {id: 36, eng: 'tree', rus: 'дерево'},
    {id: 37, eng: 'water', rus: 'вода'},
    {id: 38, eng: 'food', rus: 'еда'},
    {id: 39, eng: 'fire', rus: 'огонь'},
    {id: 40, eng: 'country', rus: 'страна'},
    {id: 41, eng: 'city', rus: 'город'},
    {id: 42, eng: 'street', rus: 'улица'},
    {id: 43, eng: 'work', rus: 'работа'},
    {id: 44, eng: 'school', rus: 'школа'},
    {id: 45, eng: 'shop', rus: 'магазин'},
    {id: 46, eng: 'house', rus: 'дом'},
    {id: 47, eng: 'room', rus: 'комната'},
    {id: 48, eng: 'car', rus: 'машина'},
    {id: 49, eng: 'paper', rus: 'бумага'},
    {id: 50, eng: 'pen', rus: 'ручка'},
    {id: 51, eng: 'door', rus: 'дверь'},
    {id: 52, eng: 'chair', rus: 'стул'},
    {id: 53, eng: 'table', rus: 'стол'},
    {id: 54, eng: 'money', rus: 'деньги'},
    {id: 55, eng: 'way', rus: 'путь, способ'},
    {id: 56, eng: 'end', rus: 'конец'},
    {id: 57, eng: 'price', rus: 'цена'},
    {id: 58, eng: 'question', rus: 'вопрос'},
    {id: 59, eng: 'answer', rus: 'ответ'},
    {id: 60, eng: 'number', rus: 'номер'},
]

export const game = {
    correct: 0,
    wrong: 0
}
