import {IWordDTO} from "../models/WordDTO";

export const database = [
    {id: 5, eng: 'I', rus: 'я'},
    {id: 6, eng: 'you', rus: 'ты, вы'},
    {id: 7, eng: 'he', rus: 'он'},
    {id: 8, eng: 'she', rus: 'она'},
    {id: 9, eng: 'it', rus: 'оно'},
    {id: 10, eng: 'we', rus: 'мы'},
    {id: 11, eng: 'people', rus: 'люди'},
    {id: 12, eng: 'family', rus: 'семья'},
    {id: 13, eng: 'woman', rus: 'женщина'},
    {id: 14, eng: 'man', rus: 'мужчина'},
    {id: 15, eng: 'girl', rus: 'девочка'},
    {id: 16, eng: 'boy', rus: 'мальчик'},
    {id: 17, eng: 'child', rus: 'ребёнок'},
    {id: 18, eng: 'friend', rus: 'друг'},
    {id: 19, eng: 'husband', rus: 'муж'},
    {id: 20, eng: 'wife', rus: 'жена'},
    {id: 21, eng: 'name', rus: 'имя'},
    {id: 22, eng: 'head', rus: 'голова'},
    {id: 23, eng: 'face', rus: 'лицо'},
    {id: 24, eng: 'hand', rus: 'рука'},
    {id: 25, eng: 'life', rus: 'жизнь'},
    {id: 26, eng: 'hour', rus: 'час'},
    {id: 27, eng: 'week', rus: 'неделя'},
    {id: 28, eng: 'day', rus: 'день'},
    {id: 29, eng: 'night', rus: 'ночь'},
    {id: 30, eng: 'month', rus: 'месяц'},
    {id: 31, eng: 'year', rus: 'год'},
    {id: 32, eng: 'time', rus: 'время'},
    {id: 33, eng: 'world', rus: 'мир'},
    {id: 34, eng: 'sun', rus: 'солнце'},
    {id: 35, eng: 'animal', rus: 'животное'},
    {id: 36, eng: 'tree', rus: 'дерево'},
    {id: 37, eng: 'water', rus: 'вода'},
    {id: 38, eng: 'food', rus: 'еда'},
    {id: 39, eng: 'fire', rus: 'огонь'},
    {id: 40, eng: 'country', rus: 'страна'},
    {id: 41, eng: 'city', rus: 'город'},
    {id: 42, eng: 'street', rus: 'улица'},
    {id: 43, eng: 'work', rus: 'работа'},
    {id: 44, eng: 'school', rus: 'школа'},
    {id: 45, eng: 'shop', rus: 'магазин'},
    {id: 46, eng: 'house', rus: 'дом'},
    {id: 47, eng: 'room', rus: 'комната'},
    {id: 48, eng: 'car', rus: 'машина'},
    {id: 49, eng: 'paper', rus: 'бумага'},
    {id: 50, eng: 'pen', rus: 'ручка'},
    {id: 51, eng: 'door', rus: 'дверь'},
    {id: 52, eng: 'chair', rus: 'стул'},
    {id: 53, eng: 'table', rus: 'стол'},
    {id: 54, eng: 'money', rus: 'деньги'},
    {id: 55, eng: 'way', rus: 'путь, способ'},
    {id: 56, eng: 'end', rus: 'конец'},
    {id: 57, eng: 'price', rus: 'цена'},
    {id: 58, eng: 'question', rus: 'вопрос'},
    {id: 59, eng: 'answer', rus: 'ответ'},
    {id: 60, eng: 'number', rus: 'номер'},
    {id: 61, eng: 'be', rus: 'быть'},
    {id: 62, eng: 'have', rus: 'иметь'},
    {id: 63, eng: 'do', rus: 'делать'},
    {id: 64, eng: 'get', rus: 'получать'},
    {id: 65, eng: 'can', rus: 'мочь'},
    {id: 66, eng: 'feel', rus: 'чувствовать'},
    {id: 67, eng: 'live', rus: 'жить'},
    {id: 68, eng: 'love', rus: 'любить'},
    {id: 69, eng: 'want', rus: 'хотеть'},
    {id: 70, eng: 'run', rus: 'бежать'},
    {id: 71, eng: 'say', rus: 'сказать'},
    {id: 72, eng: 'tell', rus: 'говорить'},
    {id: 73, eng: 'see', rus: 'видеть'},
    {id: 74, eng: 'hear', rus: 'слышать'},
    {id: 75, eng: 'listen to', rus: 'слушать'},
    {id: 76, eng: 'believe', rus: 'верить'},
    {id: 77, eng: 'take', rus: 'брать'},
    {id: 78, eng: 'give', rus: 'давать'},
    {id: 79, eng: 'go', rus: 'идти'},
    {id: 80, eng: 'walk', rus: 'гулять'},
    {id: 81, eng: 'come', rus: 'приходить'},
    {id: 82, eng: 'leave', rus: 'покидать'},
    {id: 83, eng: 'sit', rus: 'сидеть'},
    {id: 84, eng: 'stand', rus: 'стоять'},
    {id: 85, eng: 'make', rus: 'делать'},
    {id: 86, eng: 'know', rus: 'знать'},
    {id: 87, eng: 'understand', rus: 'понимать'},
    {id: 88, eng: 'remember', rus: 'помнить'},
    {id: 89, eng: 'think', rus: 'думать'},
    {id: 90, eng: 'bring', rus: 'приносить'},
    {id: 91, eng: 'find', rus: 'находить'},
    {id: 92, eng: 'lose', rus: 'терять'},
    {id: 93, eng: 'use', rus: 'использовать'},
    {id: 94, eng: 'work', rus: 'работать'},
    {id: 95, eng: 'study', rus: 'учиться'},
    {id: 96, eng: 'learn', rus: 'учить'},
    {id: 97, eng: 'ask', rus: 'спрашивать'},
    {id: 98, eng: 'answer', rus: 'ответить'},
    {id: 99, eng: 'let', rus: 'позволять'},
    {id: 100, eng: 'help', rus: 'помогать'},
    {id: 101, eng: 'begin', rus: 'начинать'},
    {id: 102, eng: 'play', rus: 'играть'},
    {id: 103, eng: 'write', rus: 'писать'},
    {id: 104, eng: 'read', rus: 'читать'},
    {id: 105, eng: 'turn', rus: 'поворачивать'},
    {id: 106, eng: 'meet', rus: 'встретить'},
    {id: 107, eng: 'change', rus: 'изменить'},
    {id: 108, eng: 'stop', rus: 'останавливать'},
    {id: 109, eng: 'open', rus: 'открыть'},
    {id: 110, eng: 'close', rus: 'закрыть'},
    {id: 111, eng: 'always', rus: 'всегда'},
    {id: 112, eng: 'never', rus: 'никогда'},
    {id: 113, eng: 'also', rus: 'также'},
    {id: 114, eng: 'just', rus: 'только что, просто'},
    {id: 115, eng: 'only', rus: 'только'},
    {id: 116, eng: 'again', rus: 'опять'},
    {id: 117, eng: 'often', rus: 'часто'},
    {id: 118, eng: 'still', rus: 'всё ещё'},
    {id: 119, eng: 'already', rus: 'уже'},
    {id: 120, eng: 'almost', rus: 'почти'},
    {id: 121, eng: 'enough', rus: 'достаточно'},
    {id: 122, eng: 'very', rus: 'очень'},
    {id: 123, eng: 'now', rus: 'сейчас'},
    {id: 124, eng: 'then', rus: 'тогда'},
    {id: 125, eng: 'usually', rus: 'обычно'},
    {id: 126, eng: 'quickly', rus: 'быстро'},
    {id: 127, eng: 'slowly', rus: 'медленно'},
    {id: 128, eng: 'well', rus: 'хорошо'},
    {id: 129, eng: 'especially', rus: 'особенно'},
    {id: 130, eng: 'sometimes', rus: 'иногда'},
    {id: 131, eng: 'good', rus: 'хороший'},
    {id: 132, eng: 'bad', rus: 'плохой'},
    {id: 133, eng: 'new', rus: 'новый'},
    {id: 134, eng: 'young', rus: 'молодой'},
    {id: 135, eng: 'old', rus: 'старый'},
    {id: 136, eng: 'big', rus: 'большой'},
    {id: 137, eng: 'small', rus: 'маленький'},
    {id: 138, eng: 'long', rus: 'длинный'},
    {id: 139, eng: 'low', rus: 'низкий'},
    {id: 140, eng: 'high', rus: 'высокий'},
    {id: 141, eng: 'strong', rus: 'сильный'},
    {id: 142, eng: 'free', rus: 'свободный'},
    {id: 143, eng: 'open', rus: 'открытый'},
    {id: 144, eng: 'easy', rus: 'лёгкий'},
    {id: 145, eng: 'right', rus: 'верный'},
    {id: 146, eng: 'wrong', rus: 'неверный'},
    {id: 147, eng: 'hot', rus: 'горячий'},
    {id: 149, eng: 'cold', rus: 'холодный'},
    {id: 150, eng: 'happy', rus: 'счастливый'},
    {id: 151, eng: 'ready', rus: 'готовый'},
]

export const game = {
    correct: 0,
    wrong: 0
}

export const phrases: IWordDTO[] = [
    {id: 1, eng: 'Hello', rus: 'Здравствуйте!'},
    {id: 2, eng: 'Hi', rus: 'Привет!'},
    {id: 3, eng: 'Good morning', rus: 'Доброе утро!'},
    {id: 4, eng: 'Good afternoon', rus: 'Добрый день!'},
    {id: 5, eng: 'Good evening', rus: 'Добрый вечер!'},
    {id: 6, eng: 'Goodbye', rus: 'До свидания!'},
    {id: 7, eng: 'Bye', rus: 'Пока!'},
    {id: 8, eng: 'Good night', rus: 'Спокойной ночи!'},
    {id: 9, eng: 'See you', rus: 'До встречи!'},
    {id: 10, eng: 'Have a nice day', rus: 'Хорошего дня!'},
    {id: 11, eng: 'Please', rus: 'пожалуйста'},
    {id: 12, eng: 'Thank you', rus: 'спасибо'},
    {id: 13, eng: 'Thank you very much', rus: 'большое спасибо'},
    {id: 14, eng: 'You\'re welcome', rus: 'пожалуйста, не за что'},
    {id: 15, eng: 'Don\'t mention it', rus: 'не стоит благодарности'},
    {id: 16, eng: 'I’m sorry', rus: 'извините'},
    {id: 17, eng: 'No problem', rus: 'ничего страшного'},
    {id: 18, eng: 'It\'s ok', rus: 'все в порядке'},
    {id: 19, eng: 'Don\'t worry about it', rus: 'не стоит беспокойства'},

    {id: 20, eng: 'Do you speak English?', rus: 'Вы говорите по-английски?'},
    {id: 21, eng: 'I don\'t speak English', rus: 'Я не говорю по-английски'},
    {id: 22, eng: 'I speak a little English', rus: 'Я немного говорю по-английски'},
    {id: 23, eng: 'Please speak more slowly', rus: 'Пожалуйста, говорите помедленнее'},
    {id: 24, eng: 'Could you please repeat that?', rus: 'Повторите, пожалуйста'},
    {id: 25, eng: 'I understand', rus: 'Я понимаю'},
    {id: 26, eng: 'I don\'t understand', rus: 'Я не понимаю'},
    {id: 27, eng: 'What\'s this?', rus: 'Что это?'},
    {id: 28, eng: 'Have you got a minute?', rus: 'У вас есть минутка?'},
    {id: 29, eng: 'Can you help me?', rus: 'Вы не могли бы мне помочь?'},

    {id: 30, eng: 'Help!', rus: 'Помогите!'},
    {id: 31, eng: 'Be careful!', rus: 'Будьте осторожны!'},
    {id: 32, eng: 'I need help', rus: 'Мне нужна помощь'},
    {id: 33, eng: 'Call the police!', rus: 'Вызовите полицию!'},
    {id: 34, eng: 'I\'m lost', rus: 'Я заблудился'},
    {id: 35, eng: 'Please leave me alone', rus: 'Пожалуйста, оставьте меня в покое'},
    {id: 36, eng: 'I don’t agree (with you)', rus: 'Я не согласен (с вами)'},
    {id: 37, eng: 'I don’t think so', rus: 'Я так не думаю'},
    {id: 38, eng: 'Are you kidding?', rus: 'Ты шутишь?'},
    {id: 39, eng: 'In my opinion', rus: ' На мой взгляд'},

    {id: 40, eng: 'What are you looking for?', rus: 'Что вы ищете?'},
    {id: 41, eng: 'Could you help me, please?', rus: 'Не могли бы вы мне помочь, пожалуйста?'},
    {id: 42, eng: 'How much will it cost?', rus: 'Сколько это будет стоить?'},
    {id: 43, eng: 'Have you any accommodation?', rus: 'У вас есть свободные номера?'},
    {id: 44, eng: 'Your room is number 25', rus: 'Номер вашей комнаты 25'},
    {id: 45, eng: 'Please leave me alone', rus: 'Пожалуйста, оставьте меня в покое'},
    {id: 46, eng: 'How much is it?', rus: 'Сколько стоит?'},
    {id: 47, eng: 'I\'ll take this', rus: 'Я возьму это'},
    {id: 48, eng: 'Do you have any another colour?', rus: 'У вас есть другой цвет?'},
    {id: 49, eng: 'I\'m just looking', rus: 'Я просто смотрю'},
    {id: 50, eng: 'Anything else?', rus: 'Что-нибудь еще?'},
]
